name: flutter_system_ringtones_advanced
description: Retrieve system ringtones, alarms, and notification sounds on Android using native APIs.
version: 2.0.0
homepage: https://github.com/nafiskabbo/flutter_system_ringtones_advanced
repository: https://github.com/nafiskabbo/flutter_system_ringtones_advanced
issue_tracker: https://github.com/nafiskabbo/flutter_system_ringtones_advanced/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kabbodev.flutter_system_ringtones
        pluginClass: FlutterSystemRingtonesPlugin
